### ISSUE TITLE
Function not uploading , ports not getting mapped

### ISSUE THREAD

**Issue by Anshul2029** [OpenFogStack/tinyFaaS#13]
Hey there , 
I had an issue of the function not uploading, it showed me few errors. The image was created in the docker.

/tinyFaaS-master$ ./src/scripts/upload.sh "./examples/sieve-of-erasthostenes" "sieve" 1
  adding: index.js (deflated 38%)
  adding: package.json (deflated 11%)
curl: (7) Failed to connect to localhost port 8080: Connection refused 

The exposed ports (8000 , 80 ,6000 , 7000) weren't getting mapped to docker port 8080.
Is there any solution for it?

**Comment by pfandzelter** [comment]
Hi @Anshul2029, thanks for trying out tinyFaaS! The error looks like port 8080 from the management service is not getting mapped to your hosts port 8080. Are you starting tinyFaaS with `make`? When you run `docker ps`, do you see the management service running and the port exposed on your host?

**Comment by Anshul2029** [comment]
Yes @pfandzelter , I started tinyFaaS with make. No, after running  docker ps , there are no containers shown.

**Comment by pfandzelter** [comment]
The error message you see is expected, as the management service only works when starting with docker. This is what happens in the makefile. You can try to execute the commands manually:

```sh
docker build -t tinyfaas-mgmt ./src/
docker build ./src/reverse-proxy
docker pull node:10-alpine
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -p 8080:8080 --name tinyfaas-mgmt -d tinyfaas-mgmt tinyfaas-mgmt
docker ps
```

And see if there are any error message you see there

**Comment by Anshul2029** [comment]
No error there , but it doesn't show the container running. 
docker ps -a
gives me the output ,

CONTAINER ID   IMAGE           COMMAND                  CREATED         STATUS                     PORTS     NAMES
96f7958b62f2   tinyfaas-mgmt   "python ./management…"   6 minutes ago   Exited (1) 4 minutes ago             tinyfaas-mgmt

**Comment by pfandzelter** [comment]
The issue was a change in the base Python image we use (updated from 3.8 to 3.9). I set this to a fixed version and updated everything!

**Comment by Anshul2029** [comment]
Thank you @pfandzelter , that issue is solved and I can upload the functions without any error, but the list doesnt display the functions added in it.

**Comment by pfandzelter** [comment]
I'm guessing this is happening when you add a function shortly after starting tinyFaaS. When you start it for the first time, the reverse proxy container is built. Adding a function during that time leads to the function not being uploaded correctly. I am adding an additional step before starting tinyFaaS that caches a built reverse proxy in #15, so startup should be a bit quicker.

**Comment by Anshul2029** [comment]
@pfandzelter  The code works on Mac but not on ubuntu

**Comment by Anshul2029** [comment]
@pfandzelter any changes suggested to make the upload function work in linux?

**Comment by pfandzelter** [comment]
What exactly isn't working? without a detailed error log I can't provide any help

**Comment by Anshul2029** [comment]
> What exactly isn't working? without a detailed error log I can't provide any help

I edited in the last comment

**Comment by Anshul2029** [comment]
Shall I consider opening it as an issue? @pfandzelter
