### ISSUE TITLE
Error 500 while uploading sample function on linux

### ISSUE THREAD

**Issue by Anshul2029** [OpenFogStack/tinyFaaS#16]
This was the following error while running the upload function on ubuntu system.  Same function might work on MacOS. Anyone help resolve this issue?
```
$ ./src/scripts/upload.sh "./examples/sieve-of-erasthostenes" "sieve" 1
  adding: index.js (deflated 38%)
  adding: package.json (deflated 11%)
<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>
```
The containers were running fine -
```
CONTAINER ID   IMAGE           COMMAND                  CREATED        STATUS        PORTS                                                                                                                                 NAMES
6381c9b3f7b2   6e1d98245647    "./app"                  11 hours ago   Up 11 hours   80/tcp, 0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 0.0.0.0:5683->6000/udp, :::5683->6000/udp, 0.0.0.0:80->7000/tcp, :::80->7000/tcp   tinyfaas-reverse-proxy
bb96b918188c   tinyfaas-mgmt   "python ./management…"   11 hours ago   Up 11 hours   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                                                                             tinyfaas-mgmt
```
Port 8080 was working properly when run with localhost:8080/list which returned an empty list on browser. The problems seems to be on upload function. Any help on this would be appreciated.

**Comment by pfandzelter** [comment]
Hi @Anshul2029, thanks for creating this issue. Please apologize the extremely late reply. I was able to reproduce this issue in Linux (but not in macOS): the main errors were not having the `zip` utility installed (`sudo apt-get install -y zip`) and newlines (`\n`) by `base64` that the macOS version doesn't produce. I have updated the scripts to take care of this and was able to run them successfully.
